---
- name: Hello World Playbook
  hosts: localhost
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, World!"
      register: job_result
    - name: Wait for Some Time
      pause:
        seconds: 10 
