---
- name: Retry Failed Job
  hosts: localhost
  gather_facts: false
  tasks:   
    - name: Rerun Failed Job
      uri:
        url: "http://localhost:32344/#/templates/job_template/9/launch/"
        method: POST
        headers:
          Authorization: "Bearer 7SZICK2xLytyEb1AzqNl0gq0PuVMxm"
        status_code: 202
        return_content: yes
      register: job_run
Write_token: T7zM6nqO46O3D5oRP2G8IEKOYIst6p
Read_token: hZErlZIgGJyulYSJBwnfnpDQBwFxo6
