---
- name: Retry Failed Job
  hosts: localhost
  gather_facts: false
  tasks:   
    - name: Rerun Failed Job
      uri:
        url: "http://localhost:32344/#/templates/job_template/9/launch/"
        method: POST
        headers:
          Authorization: "Bearer O17fjPqHArwkjZwI94BCj9SPsV4qRM"
        status_code: 202
        return_content: yes
      register: job_run
