---
- name: Retry Failed Job
  hosts: localhost
  gather_facts: false
  tasks:   
    - name: Rerun Failed Job
      uri:
        url: "http://52.139.185.126:30000/#/templates/job_template/10/launch/"
        method: POST
        headers:
          Authorization: "Bearer 5w0ae9QtqueJijrTyYMvsGJ3iztat6"
        status_code: 202
        return_content: yes
      register: job_run
