---
- hosts: localhost
  gather_facts: no  # Since we don't need facts for this example
  
  tasks:
    - name: "Register current job ID"
      set_stats:
        data:
          node1_job_id: "{{ ansible_job_id }}"
